"""Generates the two headers lannative.c needs.
  version_exports.h   - forwards every export of the real System32\version.dll (this DLL is installed AS version.dll, the game imports it)
  lannative_targets.h - RVA, stolen byte count and the expected original prologue bytes of each hook target (verified before patching)
python gen_headers.py   (needs: pip install pefile capstone)"""
import os, sys, struct, pefile
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "disasm"))
HERE = os.path.dirname(os.path.abspath(__file__))
EXE = r"C:\Program Files (x86)\Steam\steamapps\common\Absolver\Absolver\Binaries\Win64\Absolver-Win64-Shipping.exe"

# 1. proxy exports -------------------------------------------------------------------------------------------------
sysdll = pefile.PE(r"C:\Windows\System32\version.dll")
lines = ["// generated by gen_headers.py: forwards every export to the real version.dll in System32"]
for e in sysdll.DIRECTORY_ENTRY_EXPORT.symbols:
    if e.name:
        n = e.name.decode()
        BS = chr(92) * 2   # two backslashes in the C string literal = one real backslash in the path
        path = "C:" + BS + "Windows" + BS + "System32" + BS + "version."
        lines.append('#pragma comment(linker, "/export:%s=%s%s,@%d")' % (n, path, n, e.ordinal))
open(os.path.join(HERE, "version_exports.h"), "w").write("\n".join(lines) + "\n")
print(len(lines) - 1, "exports forwarded")

# 2. hook targets ----------------------------------------------------------------------------------------------------
TARGETS = [  # name, rva, stolen (from tools/sifuhook/gen_targets.py: shortest instruction-aligned prefix >= 14 bytes, no rip-relative/branch)
    ("UGameEngine_Tick", 0x145F450, 14),
    ("APlayerController_ClientRestart_Implementation", 0x1663D30, 16),
    ("APlayerController_ServerAcknowledgePossession_Implementation", 0x167A3D0, 15),
    ("AThePlainesGameMode_Logout", 0x3D7B80, 15),
    ("UEngine_SetClientTravel", 0x17B5D00, 20),
    ("AActor_Destroy", 0x122F9C0, 15),
    ("APlayerController_OnNetCleanup", 0x1675520, 16),
    ("UThePlainesGameInstance_BPF_ReturnToPreviousMap", 0x3C08B0, 18),   # M3.5 LAN-PvP guard: 18 bytes end exactly after `sub rsp,0x90`, no branch before it
    ("UDefenseComponent_NotifyParrySuccessful", 0x33F3E0, 14),           # M3.5 parry observer: 14 bytes end exactly after `push r14`
    ("UGameViewportClient_PostRender", 0x147EFF0, 14),                   # M4.0 menu text: (viewport, UCanvas *); 14 bytes end exactly after `test byte ptr [rcx+0x74],1`
    ("AAdversarialPlayerState_ScoreKill", 0x3E20E0, 16),                  # M4.3: (this, victim player state, points) - the duel kill score; 16 bytes end after `mov rbx,rcx`, next is the call
]
pe = pefile.PE(EXE)
img = open(EXE, "rb").read()
def file_off(rva):
    for s in pe.sections:
        if s.VirtualAddress <= rva < s.VirtualAddress + s.Misc_VirtualSize:
            return rva - s.VirtualAddress + s.PointerToRawData
    raise ValueError(hex(rva))
out = ["// generated by gen_headers.py (exe: Absolver 1.31 b1.25_575). The DLL refuses to patch if the live bytes differ.",
       "typedef struct { const char *name; unsigned rva; unsigned stolen; unsigned char bytes[24]; } Target;",
       "static const Target g_targets[] = {"]
for name, rva, stolen in TARGETS:
    b = img[file_off(rva): file_off(rva) + stolen]
    out.append(f'    {{ "{name}", 0x{rva:X}, {stolen}, {{ {", ".join("0x%02X" % x for x in b)} }} }},')
out.append("};")
open(os.path.join(HERE, "lannative_targets.h"), "w").write("\n".join(out) + "\n")
print(len(TARGETS), "targets written")
